### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by IeP4nieF** [petterreinholdtsen/kodi-invidious-plugin#4]
Hi and many thanks for this plugin!

After installing the plugin an all of the dependencies on Kodi 20.2 running on osmc "Trending" and "Popular" work fine. But clicking on "Search->New Search->enter a search term->ok" leeds to an error. Here are the logs:

```
2023-08-10 21:34:39.240 T:7051    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: '/home/osmc/.kodi/userdata/addon_data/plugin.video.invidious/search-history.json'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.invidious/resources/lib/invidious_addon.py", line 18, in <module>
                                                       sys.exit(main())
                                                     File "/home/osmc/.kodi/addons/plugin.video.invidious/resources/lib/invidious_addon.py", line 14, in main
                                                       return plugin.run()
                                                     File "/home/osmc/.kodi/addons/plugin.video.invidious/resources/lib/invidious_plugin.py", line 285, in run
                                                       self.display_new_search()
                                                     File "/home/osmc/.kodi/addons/plugin.video.invidious/resources/lib/invidious_plugin.py", line 158, in display_new_search
                                                       self.display_search_result(search_input)
                                                     File "/home/osmc/.kodi/addons/plugin.video.invidious/resources/lib/invidious_plugin.py", line 164, in display_search_result
                                                       self.search_history.push(search_input)
                                                     File "/home/osmc/.kodi/addons/plugin.video.invidious/resources/lib/invidious_plugin.py", line 44, in push
                                                       with open(self.history_path, "w+") as file:
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/home/osmc/.kodi/userdata/addon_data/plugin.video.invidious/search-history.json'
                                                   -->End of Python script error report<--
                                                   
2023-08-10 21:34:39.250 T:2911     info <general>: CActiveAESink::OpenSink - initialize sink
2023-08-10 21:34:39.251 T:2911     info <general>: CAESinkALSA::Initialize - Requested layout FL, FR
2023-08-10 21:34:39.251 T:2911     info <general>: CAESinkALSA::Initialize - set digital codec 0
2023-08-10 21:34:39.253 T:2911     info <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2023-08-10 21:34:39.260 T:2911     info <general>: CAESinkALSA::Initialize - Opened device "default"
2023-08-10 21:34:39.261 T:2911     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-08-10 21:34:39.261 T:2911     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4
2023-08-10 21:34:39.263 T:2911     info <general>: CAESinkALSA::Initialize - speaker layout 0
2023-08-10 21:34:39.434 T:7049    error <general>: GetDirectory - Error getting plugin://plugin.video.invidious/?action=new_search
2023-08-10 21:34:39.447 T:2893    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.invidious/?action=new_search) failed
```
Please let me know if I could debug something more.

**Comment by petterreinholdtsen** [comment]
Thank you for letting me know.  The error is rather strange, as open() with "w+" should create the file if it is missing.  This work with my LibreELEC installation.  Which environment are you using?

Do you have the /home/osmc/.kodi/userdata/addon_data/plugin.video.invidious/search-history.json file or the 
/home/osmc/.kodi/userdata/addon_data/plugin.video.invidious/ directory?  Is it working if you create the directory?

**Comment by IeP4nieF** [comment]
I'm using osmc on the vero 4k (https://osmc.tv/vero/).

`/home/osmc/.kodi/userdata/addon_data/plugin.video.invidious/` did not exists. After creating this directory the search works! Thanks!

**Comment by petterreinholdtsen** [comment]
[IeP4nieF]
> I'm using osmc on the vero 4k (https://osmc.tv/vero/).

Good to know.  I have no experience with it.

> `/home/osmc/.kodi/userdata/addon_data/plugin.video.invidious/` did not
> exists. After creating this directory the search works! Thanks!

Very good.

As LibreELEC create this directory, while osmc apparently do not, could
it be a problem with osmc, not this add-on?  I do not know the inner
workings of Kodi enough to know who is responsible for creating the
directory.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by IeP4nieF** [comment]
> Very good. As LibreELEC create this directory, while osmc apparently do not, could it be a problem with osmc, not this add-on? I do not know the inner workings of Kodi enough to know who is responsible for creating the directory.

I'm sorry, but I can't help. I don't know how Kodi-plugins works and I also only know Perl not Python.

But my suggestion would be to check for the existens of the directory before you open the file. If it doesn't exist, then create the directory first. The only disadvantage is a little bit longer code (afaik).
